
# Use an official PHP image as base
FROM php:8.1-fpm

# Set the working directory
WORKDIR /var/www/html

# Install dependencies
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    unzip \
    libzip-dev \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Node.js and npm
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy the composer files separately to leverage Docker caching
COPY composer.json composer.lock /var/www/html/

# Install PHP dependencies
RUN composer install --no-scripts --no-autoloader

# Copy the application code
COPY . /var/www/html

# Generate Laravel key
RUN php artisan key:generate

# Set proper permissions
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Install npm dependencies and build assets
RUN npm install && npm run production

# Run database migrations and seed (modify as needed)
RUN php artisan migrate --seed

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# Create MySQL database and user
RUN service mysql start \
    && mysql -u root -p -e "CREATE DATABASE IF NOT EXISTS velflix;" \
    && mysql -u root -p -e "CREATE USER 'velflix'@'%' IDENTIFIED BY '123@123';" \
    && mysql -u root -p -e "GRANT ALL PRIVILEGES ON velflix.* TO 'velflix'@'%';" \
    && mysql -u root -p -e "FLUSH PRIVILEGES" \
     

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Start PHP-FPM
CMD ["php-fpm"]
CMD ["php", "artisan", "serve", "--host", "0.0.0.0", "--port", "9000"]
